export const ErrorCodes = Object.freeze({
  // 通用参数与运行时错误。
  UNKNOWN: 'UNKNOWN', // 无法归类的未知错误。
  INVALID_ARGUMENT: 'INVALID_ARGUMENT', // 调用参数缺失、格式错误或取值非法。
  OPERATION_CANCELLED: 'OPERATION_CANCELLED', // 已排队的设备操作因任务失效而取消。
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED', // 当前能力尚未实现。

  // 系统蓝牙能力、权限和 App 级 BLE 会话错误。
  BLE_NOT_SUPPORTED: 'BLE_NOT_SUPPORTED', // 当前设备或运行环境不支持 BLE。
  PERMISSION_DENIED: 'PERMISSION_DENIED', // 用户或系统未授予所需蓝牙权限。
  SYSTEM_BLUETOOTH_DISABLED: 'SYSTEM_BLUETOOTH_DISABLED', // 系统蓝牙当前处于关闭状态。
  SYSTEM_BLUETOOTH_UNSUPPORTED: 'SYSTEM_BLUETOOTH_UNSUPPORTED', // 系统不支持请求的蓝牙开关操作。
  SYSTEM_BLUETOOTH_ENABLE_DENIED: 'SYSTEM_BLUETOOTH_ENABLE_DENIED', // 开启系统蓝牙的请求被拒绝。
  SYSTEM_BLUETOOTH_DISABLE_DENIED: 'SYSTEM_BLUETOOTH_DISABLE_DENIED', // 关闭系统蓝牙的请求被拒绝。
  SYSTEM_BLUETOOTH_CHANGE_TIMEOUT: 'SYSTEM_BLUETOOTH_CHANGE_TIMEOUT', // 等待系统蓝牙状态变化超时。
  APP_BLE_SESSION_CLOSED: 'APP_BLE_SESSION_CLOSED', // App 级共享 BLE 会话尚未打开或已关闭。
  ACTIVE_CONNECTIONS_EXIST: 'ACTIVE_CONNECTIONS_EXIST', // 仍存在活动连接，当前操作不能执行。
  ADAPTER_OPEN_FAILED: 'ADAPTER_OPEN_FAILED', // 打开 BLE 适配器失败。
  ADAPTER_CLOSE_FAILED: 'ADAPTER_CLOSE_FAILED', // 关闭 BLE 适配器失败。
  APP_SHUTTING_DOWN: 'APP_SHUTTING_DOWN', // App BLE 管理器正在关闭，拒绝新操作。

  // 共享扫描、连接和 GATT（通用属性协议）操作错误。
  SCAN_START_FAILED: 'SCAN_START_FAILED', // 启动蓝牙扫描失败。
  SCAN_STOP_FAILED: 'SCAN_STOP_FAILED', // 停止蓝牙扫描失败。
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND', // 未找到指定蓝牙设备。
  CONNECT_FAILED: 'CONNECT_FAILED', // 建立 BLE 连接失败。
  CONNECT_TIMEOUT: 'CONNECT_TIMEOUT', // 建立 BLE 连接超时。
  DISCONNECT_FAILED: 'DISCONNECT_FAILED', // 断开 BLE 连接失败。
  GATT_SERVICE_NOT_FOUND: 'GATT_SERVICE_NOT_FOUND', // 未发现所需 GATT 服务。
  GATT_CHARACTERISTIC_NOT_FOUND: 'GATT_CHARACTERISTIC_NOT_FOUND', // 未发现所需 GATT 特征。
  NOTIFY_FAILED: 'NOTIFY_FAILED', // 启用或关闭特征通知失败。
  READ_FAILED: 'READ_FAILED', // 读取 GATT 特征值失败。
  WRITE_FAILED: 'WRITE_FAILED', // 写入 GATT 特征值失败。
  MTU_FAILED: 'MTU_FAILED', // 协商或读取 MTU 失败。
  UNEXPECTED_DISCONNECT: 'UNEXPECTED_DISCONNECT', // 设备发生非主动断开。

  // 打印机（printer）领域错误。
  PRINTER_ALREADY_CONNECTED: 'PRINTER_ALREADY_CONNECTED', // 已有活动打印机，必须先断开再连接另一台。
  PRINTER_NOT_CONNECTED: 'PRINTER_NOT_CONNECTED', // 当前没有已连接的打印机。
  PRINTER_NOT_READY: 'PRINTER_NOT_READY', // 打印机已连接但尚未完成业务初始化。
  PRINTER_PRINTING: 'PRINTER_PRINTING', // 打印机已有进行中的任务。
  PRINTER_PRINT_FAILED: 'PRINTER_PRINT_FAILED', // 打印任务失败或返回失败状态。
  PRINTER_PLUGIN_UNAVAILABLE: 'PRINTER_PLUGIN_UNAVAILABLE', // LPAPI 插件或所需方法不可用。

  // 电子秤（scale）领域错误。
  SCALE_ALREADY_CONNECTED: 'SCALE_ALREADY_CONNECTED', // 已连接电子秤，不能重复连接另一台。
  SCALE_NOT_CONNECTED: 'SCALE_NOT_CONNECTED', // 当前没有已连接的电子秤。
  SCALE_NOT_READY: 'SCALE_NOT_READY', // 已连接，但 GATT 或协议尚未准备完成。
  SCALE_PROFILE_NOT_FOUND: 'SCALE_PROFILE_NOT_FOUND', // 未匹配到可验证的电子秤协议配置。
  SCALE_SERVICE_NOT_FOUND: 'SCALE_SERVICE_NOT_FOUND', // 未找到电子秤所需的 GATT 服务。
  SCALE_WEIGHT_CHARACTERISTIC_NOT_FOUND: 'SCALE_WEIGHT_CHARACTERISTIC_NOT_FOUND', // 未找到读取重量所需的特征。
  SCALE_FRAME_INVALID: 'SCALE_FRAME_INVALID', // 收到的电子秤协议帧格式或校验无效。
  SCALE_WEIGHT_INVALID: 'SCALE_WEIGHT_INVALID', // 协议帧中的重量值无法有效解析。
  SCALE_OVERLOAD: 'SCALE_OVERLOAD', // 电子秤返回 OL 超载状态。
  SCALE_WEIGHT_READ_FAILED: 'SCALE_WEIGHT_READ_FAILED', // 发送读取命令或等待单次重量响应失败。
  SCALE_STABLE_TIMEOUT: 'SCALE_STABLE_TIMEOUT', // 等待稳定重量超时。
});