import { describe, expect, it, vi } from 'vitest';
import { sha256, TransferManager } from '../../src/bridge/transfer';
const content='QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo=';
function fake(){const handlers:any={};return{handlers,register:(n:string,h:any)=>{handlers[n]=h;return()=>delete handlers[n]},call:vi.fn(),getSnapshot:()=>({sessionId:'s1',generation:1})} as any;}
const meta=(id='t1')=>({transferId:id,sessionId:'s1',generation:1,action:'printer_preview',field:'image',mime:'image/png',encodedChars:content.length,decodedBytes:26,chunks:2,sha256:sha256(content)});
const ctx={sessionId:'s1',generation:1};
describe('H5 transfer manager',()=>{
 it('reassembles out of order, duplicate chunks and consumes once',async()=>{const c=fake(),m=new TransferManager(c),a=content.slice(0,16),b=content.slice(16);await c.handlers['transfer.start'](meta(),ctx);await c.handlers['transfer.chunk']({transferId:'t1',index:1,data:b,sha256:sha256(b)},ctx);await c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},ctx);await c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},ctx);await c.handlers['transfer.complete']({transferId:'t1'},ctx);expect(m.consume({transferId:'t1'},'printer_preview')).toContain(content);expect(()=>m.consume({transferId:'t1'},'printer_preview')).toThrow();m.destroy();});
 it('rejects conflict, missing and bad hash; abort/destroy clean',async()=>{let c=fake(),m=new TransferManager(c),a=content.slice(0,16);await c.handlers['transfer.start'](meta(),ctx);await c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},ctx);expect(()=>c.handlers['transfer.chunk']({transferId:'t1',index:0,data:'AAAA',sha256:sha256('AAAA')},ctx)).toThrowError(expect.objectContaining({code:'TRANSFER_CONFLICT'}));m.destroy();c=fake();m=new TransferManager(c);await c.handlers['transfer.start'](meta(),ctx);await expect(c.handlers['transfer.complete']({transferId:'t1'},ctx)).rejects.toMatchObject({code:'TRANSFER_INCOMPLETE'});await c.handlers['transfer.abort']({transferId:'t1'},ctx);expect((m as any).items.size).toBe(0);m.destroy();});
 it('retries timeout and sends abort',async()=>{const c=fake(),m=new TransferManager(c);c.call.mockRejectedValue(Object.assign(new Error(),{code:'TIMEOUT'}));await expect(m.send(`data:image/png;base64,${content}`,'printer_preview')).rejects.toMatchObject({code:'TRANSFER_TIMEOUT'});expect(c.call).toHaveBeenCalledTimes(4);expect(c.call.mock.calls[3][0]).toBe('transfer.abort');m.destroy();});
});