import { TransferManager, sha256 } from '../js_sdk/services/transfer-manager.js'

function core() { const handlers = {}; return { handlers, register: jest.fn((n,h)=>{handlers[n]=h;return()=>delete handlers[n]}), call: jest.fn() } }
const ctx={sessionId:'s1',generation:1}
const content='QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo='
const meta=(id='t1',extra={})=>({transferId:id,sessionId:'s1',action:'printer_print',field:'image',mime:'image/png',encodedChars:content.length,decodedBytes:26,chunks:2,sha256:sha256(content),...extra})

describe('transfer manager',()=>{
 test('accepts out of order and identical duplicate then consumes once',async()=>{const c=core(),m=new TransferManager(c);await c.handlers['transfer.start'](meta(),ctx);const a=content.slice(0,16),b=content.slice(16);await c.handlers['transfer.chunk']({transferId:'t1',index:1,data:b,sha256:sha256(b)},ctx);await c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},ctx);await c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},ctx);await c.handlers['transfer.complete']({transferId:'t1'},ctx);expect(m.consume({kind:'bridge-attachment',transferId:'t1'},ctx,'printer_print')).toBe(`data:image/png;base64,${content}`);expect(()=>m.consume({kind:'bridge-attachment',transferId:'t1'},ctx,'printer_print')).toThrow(/incomplete/i);m.destroy()})
 test('rejects conflict, missing chunk and hash mismatch',async()=>{let c=core(),m=new TransferManager(c);await c.handlers['transfer.start'](meta(),ctx);const a=content.slice(0,16);await c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},ctx);await expect(c.handlers['transfer.chunk']({transferId:'t1',index:0,data:'AAAA',sha256:sha256('AAAA')},ctx)).rejects.toMatchObject({code:'TRANSFER_CONFLICT'});m.destroy();c=core();m=new TransferManager(c);await c.handlers['transfer.start'](meta(),ctx);await expect(c.handlers['transfer.complete']({transferId:'t1'},ctx)).rejects.toMatchObject({code:'TRANSFER_INCOMPLETE'});await c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},ctx);const b=content.slice(16);await c.handlers['transfer.chunk']({transferId:'t1',index:1,data:b,sha256:sha256(b)},ctx);m.items.get('t1').meta.sha256='0'.repeat(64);await expect(c.handlers['transfer.complete']({transferId:'t1'},ctx)).rejects.toMatchObject({code:'TRANSFER_HASH_MISMATCH'});m.destroy()})
 test('enforces per-session and budget; abort and destroy release state',async()=>{const c=core(),m=new TransferManager(c,{perSession:2,global:4,budget:100});await c.handlers['transfer.start'](meta('a'),ctx);await c.handlers['transfer.start'](meta('b'),ctx);await expect(c.handlers['transfer.start'](meta('c'),ctx)).rejects.toMatchObject({code:'TRANSFER_LIMIT'});await c.handlers['transfer.abort']({transferId:'a'},ctx);await c.handlers['transfer.start'](meta('c'),ctx);m.destroy();expect(m.items.size).toBe(0);await expect(c.handlers['transfer.start']?.(meta('d'),ctx) || Promise.reject({code:'BRIDGE_DESTROYED'})).rejects.toBeDefined();const c2=core(),m2=new TransferManager(c2,{budget:content.length-1});await expect(c2.handlers['transfer.start'](meta(),ctx)).rejects.toMatchObject({code:'TRANSFER_BUDGET_EXCEEDED'});m2.destroy()})
 test('rejects chunk, complete and abort from another session generation',async()=>{const c=core(),m=new TransferManager(c);await c.handlers['transfer.start'](meta(),ctx);const other={sessionId:'s2',generation:2};const a=content.slice(0,16);await expect(c.handlers['transfer.chunk']({transferId:'t1',index:0,data:a,sha256:sha256(a)},other)).rejects.toMatchObject({code:'TRANSFER_NOT_FOUND'});await expect(c.handlers['transfer.complete']({transferId:'t1'},other)).rejects.toMatchObject({code:'TRANSFER_NOT_FOUND'});await expect(c.handlers['transfer.abort']({transferId:'t1'},other)).rejects.toMatchObject({code:'TRANSFER_NOT_FOUND'});expect(m.items.has('t1')).toBe(true);m.destroy()})
 test('send retries timeout and aborts',async()=>{const c=core();c.call.mockRejectedValue(Object.assign(new Error('timeout'),{code:'TIMEOUT'}));const m=new TransferManager(c,{attempts:2,timeout:1});await expect(m.send(`data:image/png;base64,${content}`,'printer_print','image','s1')).rejects.toMatchObject({code:'TRANSFER_TIMEOUT'});expect(c.call).toHaveBeenCalledTimes(3);expect(c.call.mock.calls[2][0]).toBe('transfer.abort');m.destroy()})
})
